
@baseUrl = http://localhost:3333
@authToken = {{ authenticate.response.body.access_token }}

# @name create_account
Post {{baseUrl}}/users
content-type: application/json

{
  "email": "johnDoe@gmail.com",
  "password": "123456",
  "name": "John Doe"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
content-type: application/json

{
  "email": "johnDoe@gmail.com",
  "password": "123456"
}

###

# @name create_new_product
POST {{baseUrl}}/products
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "mesa",
  "description": "confortavel",
  "price": "1000.00",
  "category": "Eletrônicos",
  "stock": "100"
}
### 

# @name list_all_product
GET {{baseUrl}}/products
Authorization: Bearer {{authToken}}

###

# @name get_specific_product_details
GET {{baseUrl}}/products/666aa324f8dbcff69bfa776f
Authorization: Bearer {{authToken}}

###

# @name update_product_information
PUT {{baseUrl}}/products/666aa324f8dbcff69bfa776f
content-type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "garrafas",
  "price": "500",
  "category": "objeto",
  "stock": "50"
}

###

# @name delete_produto
DELETE {{baseUrl}}/products/666aa3f04756e59cd86d9e8d
Authorization: Bearer {{authToken}}
